openapi: "3.0.3"

info:
  title: "Shop Review API"
  description: |
    # Feature
    - GetReviews
    - PostReviews
  contact: 
    name: "CustomerSupport"
    url: "https://"
  license:
    name: "MIT Licence"
    url: "https://spdx.org/licenses/MIT.html"
  version: "1.0.0"

paths: {}
